### ISSUE TITLE
Undefined Index on installation

### ISSUE THREAD

**Issue by thomas-harding** [magefan/module-html-sitemap#6]
I get an error when installing the extension via composer. Magento 2.4.4, PHP 7.4

Go to Stores > Configuration

## Expected Result
I'm able to view the configuration settings for the sitemap

## Actual result

I get the error

Exception #0 (Exception): Notice: Undefined index: id in /var/www/vhosts/site/httpdocs/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

**Comment by magefan** [comment]
@thomas-harding , could you please double-check and make sure that the module https://github.com/magefan/module-community has also been installed
