### ISSUE TITLE
Getting error on my download page

### ISSUE THREAD

**Issue by devamitbera** [magefan/module-html-sitemap#8]
Hi 

Thanks for the nice work on that extension.

The extension has a bug when placing downloadable orders.

Getting error  on my download page :

```
1 exception(s):
Exception #0 (ReflectionException): Class Magefan\ThankYouForDownload\Controller\Link does not exist


```

**Comment by magefan** [comment]
Hello @devamitbera , thank you for your report. Please remove the etc/di.xml file in the module folder. We've just removed it in our code base. This change will be included in the next releases.

Let us know if this fix works for your well.

**Comment by devamitbera** [comment]
Thanks for quick work :)
